### ISSUE TITLE
建议增加从定理到推论的证明过程

### ISSUE THREAD

**Issue by ZeroAurora** [Himself65/LianXue#1]
如题（

**Comment by Himself65** [comment]
nice idea

**Comment by Himself65** [comment]
nice idea

**Comment by Himself65** [comment]
landed at https://github.com/Himself65/LianXue/commit/e7275b0e24918b9197314fd359b517dbdeaff189

**Comment by ice1000** [comment]
你可以在 commit message 里面写 `fix #1`
