### ISSUE TITLE
为什么不早点写

### ISSUE THREAD

**Issue by ciwomuli** [Himself65/LianXue#3]
我已经失去一个可爱妹子了

**Comment by Himself65** [comment]
i’m sorry to hear that. if you learn LianXue early, we promise you would lost more than one girl

**Comment by Himself65** [comment]
![image](https://user-images.githubusercontent.com/14026360/60944573-c9682180-a31b-11e9-979e-4f1d2b951e24.png)

**Comment by keepthethink** [comment]
What's LianXue?

**Comment by ice1000** [comment]
What's Lian✗ue?
